[package]
name = "blueddisk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.8"
reqwest = { version = "0.12.5", features = ["blocking"] }
